- name: Validando se o tenant {{tnt}} já existe!
  ansible.builtin.shell: curl -X GET \
    https://<url.master.3scale>/admin/api/accounts.xml \
    -d "access_token=<master.token>" -k \
    -d "state=approved" \
    -d "page=1" \
    -d "per_page=500" | xmllint --format - | grep "{{tnt}}" || /bin/true
  register: accountslist

- name: Criando o tenant {{tnt}}
  ansible.builtin.shell: curl -X POST  \
    https://<url.master.3scale>/master/api/providers.xml \
    -d "access_token=<master.token>" -k \
    -d "org_name={{tnt}}" \
    -d "username="<user>"" \
    --data-urlencode "email=<e-mail@e-mail.com.br>" \
    -d "password=<password>"
  register: tenantid
  when: accountslist.stdout == ""

- name: Coletando o token
  ansible.builtin.debug:
    msg: "{{ tenantid.stdout | regex_findall('(?:[A-Za-z0-9]{1,})(?=<\\/value>)') }}"
  register: accesstokens
  when: accountslist.stdout == ""
    
- name: Colentando a id do user para ativação
  ansible.builtin.debug:
    msg: "{{ tenantid.stdout | regex_findall('\\b(?:[0-9]{1,5}\\b)(?=<\\/id>)') }}"
  register: id
  when: accountslist.stdout == ""
  
- name: Ativando o tenant {{tnt}} e o usuário
  ansible.builtin.shell: curl -X PUT \
    https://<url.master.3scale>/admin/api/accounts/{{id.msg[0]}}/users/{{id.msg[4]}}/activate.xml \
    -d "access_token=<master.token>" -k
  when: accountslist.stdout == ""

- ansible.builtin.pause:
    seconds: 30

- name: Criando integração com o realm <realm.rhsso>
  ansible.builtin.shell: curl -X POST \
    https://<url.account.3scale>/admin/api/account/authentication_providers.xml \
    -d "access_token={{accesstokens.msg[0]}}" -k \
    -d "kind=keycloak" \
    -d "client_id=<client_id.rhsso>" \
    -d "client_secret=<secret.rhsso>" \
    -d "site=https://<url.rhsso>/auth/realms/<realm.rhsso>" \
    -d "skip_ssl_certificate_verification=True" \
    -d "published=True"
  when: accountslist.stdout == ""

- name: Salvando o token 
  ansible.builtin.lineinfile:
    path: <path>
    state: present
    line: "\nAccount: {{tnt}}-dev\ntoken: {{accesstokens.msg[0]}}"
    backup: no
  when: accountslist.stdout == ""

- name: Fazendo o commit e push do token salvo 
  ansible.builtin.shell: git pull && git add . && git commit -m "create-account-3scale" && git push
  args:
    chdir: <path>
  when: accountslist.stdout == ""